modLoader="javafml"

loaderVersion="[39,)"

license="GNU GPLv3"

issueTrackerURL="https://github.com/foozey/The-Gems-Project/issues"

[[mods]]

modId="gems"

version="1.18.1-2.0.0"

displayName="The Gems Project"

displayURL="https://www.curseforge.com/minecraft/mc-mods/the-gems-project"

logoFile="Header.png"

credits="Thanks to the Forge Project, the modding community, and Mojang!"

authors="Fooze"

description='''
A mod that focuses on adding more progression to Minecraft.
'''

[[dependencies.gems]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gems]]
	modId="curios"
    mandatory=true
    versionRange="[1.18.1-5.0.2.1,)"
    ordering="NONE"
    side="BOTH"