modLoader="javafml"

loaderVersion="[43,)"

license="LGPL-3.0-or-later"

issueTrackerURL="https://github.com/foozey/The-Gems-Project/issues"

[[mods]]

modId="gems"

version="1.19.2-3.0.1"

displayName="The Gems Project"

displayURL="https://www.curseforge.com/minecraft/mc-mods/the-gems-project"

logoFile="Header.png"

credits="Thanks to the Forge Project, the modding community, and Mojang!"

authors="Fooze"

description='''
A mod that focuses on adding more progression to Minecraft.
'''

[[dependencies.gems]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gems]]
	modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"