modLoader="javafml"
loaderVersion="${forge_version_range}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/Foozey/The-Gems-Project/issues"

[[mods]]
modId="${modid}"
version="${mc_version}-${mod_version}"
displayName="The Gems Project"
updateJSONURL="https://github.com/Foozey/The-Gems-Project/raw/1.20.x/update.json"
displayURL="https://curseforge.com/minecraft/mc-mods/the-gems-project"
logoFile="Header.png"
credits="Thanks to the modding community, Minecraft Forge, and Mojang!"
authors="Fooze"
description='''
A Minecraft mod focused on progression.
'''

[[dependencies.${modid}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="curios"
mandatory=true
versionRange="${curios_version_range}"
ordering="NONE"
side="BOTH"